### ISSUE TITLE
Why 'Graph' tab is not exist during visualization ?

### ISSUE THREAD

**Issue by lidongze0629** [aws/graph-notebook#269]
```shell
Name: graph-notebook
Version: 3.1.1
Summary: jupyter notebook extension to connect to graph databases
Home-page: https://github.com/aws/graph-notebook
Author: amazon-neptune
Author-email: amazon-neptune-pypi@amazon.com
License: UNKNOWN
Location: /Users/lidongze/Library/Python/3.9/lib/python/site-packages
Requires: boto3, botocore, gremlinpython, ipykernel, ipython, ipywidgets, jedi, Jinja2, jupyter, jupyter-contrib-nbextensions, nbconvert, neo4j, networkx, notebook, rdflib, requests, requests-aws4auth, SPARQLWrapper, widgetsnbextension
Required-by: 
```

<img width="1215" alt="截屏2022-02-24 下午4 00 43" src="https://user-images.githubusercontent.com/23491543/155483766-aba27a5d-2397-480c-aa54-e7fa2275652e.png">

<img width="1141" alt="截屏2022-02-24 下午4 08 15" src="https://user-images.githubusercontent.com/23491543/155483865-b42b82f1-d2a2-46ef-9ab9-3e7c877d1398.png">

Could someone can tell me how to visualize the graph during `gremlin` magic function like this ? thanks.
---------------------

![截屏2022-02-24 下午4 10 04](https://user-images.githubusercontent.com/23491543/155484342-7dafebff-29e7-4ec2-91c1-2d1cbbac0937.png)

**Comment by michaelnchin** [comment]
Hi @lidongze0629, for the graph tab to be rendered, the Gremlin query and the `%%gremlin` line arguments must satisfy certain conditions. 

I'll start with the second query, as it's more straightforward. For a Gremlin query result to be visualized, it must be a path. As the query `g.V()` only returns vertices, the graph tab is not displayed.

For the first query, the visualizer fails because the provided path pattern `-p v,oute,inv,oute,inv,oute,inv` expects paths containing four vertices connected by explicitly returned edges. Your query returns paths following a different sequence, three vertices with no explicit edges returned.

If we amend the path pattern to `-p v,inv,inv` to match the query results, the graph will be displayed as intended:

![Screen Shot 2022-02-24 at 10 30 05 AM](https://user-images.githubusercontent.com/10456376/155598288-405744cf-4fed-4d94-b6ef-0ad540805c57.png)

Please do take a look at our [tutorial notebooks](https://github.com/aws/graph-notebook/tree/main/src/graph_notebook/notebooks/02-Visualization), which provide excellent walkthroughs of how to use visualize queries. These notebooks are included with the graph-notebook package, you can install and launch them from a local directory by running:
```
# copy premade starter notebooks
python -m graph_notebook.notebooks.install --destination ~/notebook/destination/dir

# start jupyter
python -m graph_notebook.start_notebook --notebooks-dir ~/notebook/destination/dir
```

**Comment by lidongze0629** [comment]
@michaelnchin Thanks very much for your detailed reply, it's helpful for me.
