### ISSUE TITLE
Create a guide to setup access via SageMaker

### ISSUE THREAD

**Issue by nimrodkor** [aws/graph-notebook#38]
**Is your feature request related to a problem? Please describe.**
I'd like to connect to a Neptune cluster. The easiest thing for me would be to launch a SageMaker notebook in that VPC and work on it. However, it seems like installing the extensions is not as straight-forward as a `pip install`.

**Describe the solution you'd like**
A guide on how to install all the required dependencies, via a lifecycle configuration if possible.

**Comment by austinkline** [comment]
Thanks for submitting this ticket! This should just be a documentation change. Indeed, `pip install` is not sufficient since you also need to enable some things on the jupyter side, and we upload pip as a wheel which won't do those steps.

The recommended approach for Sagemaker would be to use our script found in s3:
`s3://aws-neptune-notebook/graph_notebook.tar.gz`

Here is a sample lifecycle configuration which makes use of it:

```
#!/bin/bash
 
sudo -u ec2-user -i <<'EOF'
 
echo "export GRAPH_NOTEBOOK_AUTH_MODE=DEFAULT" >> ~/.bashrc  # set to IAM instead of DEFAULT if cluster is IAM enabled
echo "export GRAPH_NOTEBOOK_HOST=CHANGE-ME" >> ~/.bashrc
echo "export GRAPH_NOTEBOOK_PORT=8182" >> ~/.bashrc
echo "export NEPTUNE_LOAD_FROM_S3_ROLE_ARN=" >> ~/.bashrc
echo "export AWS_REGION=us-west-2" >> ~/.bashrc
 
aws s3 cp s3://aws-neptune-notebook/graph_notebook.tar.gz /tmp/graph_notebook.tar.gz
rm -rf /tmp/graph_notebook
tar -zxvf /tmp/graph_notebook.tar.gz -C /tmp
/tmp/graph_notebook/install.sh
 
EOF
```

**Comment by joywa** [comment]
Updated docs to share sample lifecycle configuration file for use with SageMaker: https://github.com/aws/graph-notebook/tree/main/additional-databases/sagemaker

**Comment by rossjohnstone-paypay** [comment]
Hi @joywa (if you're still there) or anyone else. Is it necessary to generate the graph config in the lifecycle script?

Are these lines https://github.com/aws/graph-notebook/blob/e8d03645f6f532815db09bc06fcc0c83b907e663/additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc.sh#L76-L83

equivalent to running, for example, this in a notebook cell?:

```
%%graph_notebook_config
{
  "host": "your-neptune-endpoint",
  "neptune_service": "neptune-graph",
  "port": 443,
  "auth_mode": "IAM",
  "ssl": true,
  "ssl_verify": true,
  "aws_region": "your-neptune-region"
}
```

I would prefer not to hard-code my (Neptune Analytics) graph into the lifecycle configuration script, since I expect to delete the graph after using the notebook.

**Comment by michaelnchin** [comment]
@rossjohnstone-paypay yes, you certainly can use `%%graph_notebook_config` to manually set the connection configuration after the notebook is created. If `generate_config` is not run as part of the lifecycle, the initial configuration will be populated with placeholder values, which can be overridden.

**Comment by rossjohnstone-paypay** [comment]
Hi @michaelnchin thanks. Would you be able to share a version of the [lifecycle configuration script](https://github.com/aws/graph-notebook/blob/e8d03645f6f532815db09bc06fcc0c83b907e663/additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc-cn.sh) for use in JupyterLab within SageMaker Studio?

I tried simply executing the commands [here](https://github.com/aws/graph-notebook/tree/main?tab=readme-ov-file#jupyterlab-3x) but I'm not sure if I'm enabling the extensions within the correct instance of JupyterLab.

**Comment by michaelnchin** [comment]
@rossjohnstone-paypay I believe SageMaker Studio uses JupyterLab 4 - graph-notebook currently supports up to JupyterLab 3, so it would not be compatible at the moment.

Related issue: https://github.com/aws/graph-notebook/issues/689
