### ISSUE TITLE
[BUG] Graph tab doesn't render in Amazon SageMaker Studio - Jupyter Lab

### ISSUE THREAD

**Issue by Nivmorabin** [aws/graph-notebook#54]
**Describe the bug**
When trying to execute a .path() query in Jupyter Lab the Graph tab doesn't render, instead it shows
`"Tab(children=(Output(layout=Layout(max_height='600px', overflow='scroll', width='100%')), Force(network=<graph…"`

**To Reproduce**
1. Go to Jupyter Lab
2. Run a query with .path()

**Current behavior**
Screenshot taken from JupyterLab

![image](https://user-images.githubusercontent.com/4501996/103637313-fb2f6800-4f53-11eb-9eac-8fd446c240bf.png)

**Expected behavior**
Screenshot taken from Jupyter

![image](https://user-images.githubusercontent.com/4501996/103637180-bf949e00-4f53-11eb-8090-b2057c62cea3.png)

**Comment by austinkline** [comment]
Thanks for reaching out! We haven't taken the work to support jupyterlabs yet, though we do build our visualization widget for labs already. Seems like the Tab widget isn't being displayed properly in the screenshot provided of labs, but that could be because our Force widget isn't installed properly. 

I have cut a feature request for this: #55

**Comment by Nivmorabin** [comment]
Thanks a lot!
Appreciate it 👍

**Comment by michaelnchin** [comment]
Widgets now render properly in JupyterLab as of #271 .
